# Generated by Django 6.0.5 on 2026-05-26 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_evaluation_options_alter_faculty_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('EDUCATION', 'Education'), ('BUSINESS', 'Business'), ('HOSPITALITY', 'Hospitality')], max_length=100),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('EDUCATION', 'Education'), ('BUSINESS', 'Business'), ('HOSPITALITY', 'Hospitality')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
