# Generated by Django 6.0.5 on 2026-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_faculty_department_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
